### ISSUE TITLE
Additional controls

### ISSUE THREAD

**Issue by atlanticaccent** [atlanticaccent/starsector-mod-manager-rust#47]
- Enable all
- Disable all
- Filters
  - Only outdated
  - Only unsupported
- refresh
- filter by [name, id, etc]
- etc

**Comment by jaghaimo** [comment]
Also, `refresh` - currently, if you have the program opened and install something manually, the only way for the program to acknowledge changes is to close it and open again.

**Comment by atlanticaccent** [comment]
> Also, `refresh` - currently, if you have the program opened and install something manually, the only way for the program to acknowledge changes is to close it and open again.

It's not documented, and will probably change with #40, but opening and closing settings will refresh the mod list....

But yeah, refresh button is a good idea.
