### ISSUE TITLE
7z support

### ISSUE THREAD

**Issue by atlanticaccent** [atlanticaccent/starsector-mod-manager-rust#54]
compress-tools claims to support 7z files, but somethings seems to be going wrong there because my tests (on WSL) don't work, and it's not useable on Windows anywany.

Using the cxx crate, we may be able to either:
- build our own wrapper around the most basic libarchive functions (ew, but necessary for linux, as demonstrated in the next point)
- include the 7zip DLL and a wrapper around it, which gives us fantastically improved archive capabilities, but only on windows.

**Comment by jaghaimo** [comment]
Wouldn't this allow you to replace custom format handling with just one implementation?
https://crates.io/crates/compress-tools

**Comment by atlanticaccent** [comment]
Another option:

Use the XADMaster Obj-C library built for 'The Unarchiver' :
- https://github.com/incbee/Unarchiver/tree/bleeding-edge/XADMaster
- https://github.com/incbee/Unarchiver/tree/bleeding-edge/UniversalDetector

And a crate for Obj-C bindings:
- https://crates.io/crates/fruity (maintained, no examples)
- https://crates.io/crates/objc (popular, more mature?,  cryptic mention of alternate runtimes for cross-platform, unsafe code required)
- bindgen can maybe be mentioned here too?

**Comment by jaghaimo** [comment]
Poor-mans solution is a solution as well. Require the user to provide 7z executable (autodetect and call as external program).
