### ISSUE TITLE
Install from Archive improvements

### ISSUE THREAD

**Issue by jaghaimo** [atlanticaccent/starsector-mod-manager-rust#86]
A rather typical workflow involves opening mod manager, and download each outdated mod to a default location, only to then "Install  Mod From Archive" them one after another. This could be improved in two ways:

1. Remember last used folder during a session (or even cross-session) to cut down on time needed for folder traversal.
2. Allow for bulk install (multi-select) to cut down on repetition.

**Comment by atlanticaccent** [comment]
I believe both of these have been addressed in the latest releases so closing
